version : 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm i puppeteer
      - run: npm i http-server -g
      - run:
          name: Run server in background
          command: 'http-server'
          background: true
      - run:
          name: Run tests
          command: 'npm test'
